apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: loki-distributed
    repo: https://grafana.github.io/helm-charts
    version: 0.80.5
    releaseName: loki
    namespace: loki
    valuesFile: values-dev.yaml
