apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/eehiikkdfi470/swcom.git'
    targetRevision: main
    path: apps/loki/overlays/dev

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: loki

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

