# Ensure clean resource names like loki-distributor, loki-ingester, etc.
fullnameOverride: "loki"

# Distributor
distributor:
  replicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

# Ingester with persistent storage
ingester:
  replicas: 1
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "400m"
      memory: "1Gi"
  persistence:
    enabled: true
    claims:
      - name: data
        size: 5Gi
        storageClass: "standard"

# Querier
querier:
  replicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

# Query Frontend
queryFrontend:
  replicas: 1
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"

# Compactor with persistent storage
compactor:
  enabled: true
  kind: StatefulSet
  replicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"
  persistence:
    enabled: true
    size: 5Gi
    storageClass: "standard"

# Index Gateway with persistent storage
indexGateway:
  enabled: true
  replicas: 1
  persistence:
    enabled: true
    size: 5Gi
    storageClass: "standard"

# Gateway
gateway:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"

# Disable ruler
ruler:
  enabled: false

# Loki common storage config
loki:
  storageConfig:
    boltdb_shipper:
      shared_store: filesystem
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
    filesystem:
      directory: /var/loki/chunks

  schemaConfig:
    configs:
      - from: "2020-10-15"
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: loki_index_
          period: 24h
