# server:
#   service:
#     type: LoadBalancer

controller:
  replicaCount: 1

redis:
  enabled: true
server:
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi