apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-distributed
    targetRevision: 0.80.5
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: loki
  syncPolicy:
    syncOptions:
    - CreateNamespace=true #instruct argocd to cretae namesapce
    automated:
      prune: true
      selfHeal: true
