apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mimir

helmCharts:
  - name: mimir-distributed
    repo: https://grafana.github.io/helm-charts
    version: 5.0.0
    releaseName: mimir
    namespace: mimir
    valuesFile: values-config.yaml
