fullnameOverride: "loki"
distributor:
  replicas: 1
ingester:
  replicas: 1
  persistence:
    enabled: true
    claims:
      - name: data
        size: 5Gi
        storageClass: "standard"
querier:
  replicas: 1
queryFrontend:
  replicas: 1
compactor:
  enabled: true
  kind: StatefulSet
  replicas: 1
  persistence:
    enabled: true
    size: 5Gi
    storageClass: "standard"
indexGateway:
  enabled: true
  replicas: 1
  persistence:
    enabled: true
    size: 5Gi
    storageClass: "standard"
gateway:
  enabled: true
  replicas: 1
ruler:
  enabled: false

loki:
  structuredConfig:
    auth_enabled: false
    server:
      http_listen_port: 3100
    distributor:
      ring:
        kvstore:
          store: memberlist
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
    memberlist:
      join_members:
        - loki-memberlist
    schema_config:
      configs:
        - from: "2020-10-15"
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: loki_index_
            period: 24h
    storage_config:
      boltdb_shipper:
        shared_store: filesystem
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
      filesystem:
        directory: /var/loki/chunks
    compactor:
      working_directory: /var/loki/compactor
      shared_store: filesystem
    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
