name: Render and Deploy ArgoCD to local KIND cluster

on:
  push:
    branches:
      - main
    paths:
      - 'apps/argocd/base/application.yaml'
      - 'apps/argocd/overlays/dev/values.yaml'
  workflow_dispatch:

jobs:
  render-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set KUBECONFIG environment variable
        run: echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Ensure overlays/dev directory exists
        run: mkdir -p apps/argocd/overlays/dev

      - name: Generate rendered ArgoCD manifests
        run: |
          kubectl kustomize --enable-helm --load-restrictor LoadRestrictionsNone apps/argocd/overlays/dev > apps/argocd/overlays/dev/_rendered_argocd_latest.yaml

      - name: Apply rendered ArgoCD manifests
        run: |
          kubectl apply -f apps/argocd/overlays/dev/_rendered_argocd_latest.yaml